import type { HttpStatusCode } from './http-status-code.type'

export type ProblemDetails = {
	/**
	 * A URI reference that identifies the problem type. It's intended to provide human operators
	 * with a place to find more information about the error. If not present or applicable,
	 * it’s assumed to be “about:blank”.
	 */
	type: string
	/**
	 * The HTTP status code generated by the origin server for this occurrence of the problem.
	 */
	title: string
	/**
	 * A short, human-readable summary of the problem type. It should not change from occurrence
	 * to occurrence of the problem, except for purposes of localization.
	 */
	status: HttpStatusCode
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 * Unlike the title, this field's content can vary by occurrence.
	 */
	detail: string
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 * It may or may not yield further information if dereferenced.
	 */
	instance: string

	/**
	 * An optional object containing additional properties to provide more context about the problem.
	 */
	[key: string]: unknown
}

export type ProblemDetailsPartial = ProblemDetails & {
	title?: string
	status?: HttpStatusCode
	detail?: string
}
