import type { HttpStatusCode } from './http-status-code.type'

/**
 * Base fields defined by RFC 9457 (Problem Details for HTTP APIs).
 */
type ProblemDetailsBase = {
	/**
	 * A URI reference that identifies the problem type. It's intended to provide human operators
	 * with a place to find more information about the error. If not present or applicable,
	 * it's assumed to be "about:blank".
	 */
	type: string
	/**
	 * The HTTP status code generated by the origin server for this occurrence of the problem.
	 */
	status: HttpStatusCode
	/**
	 * A short, human-readable summary of the problem type. It should not change from occurrence
	 * to occurrence of the problem, except for purposes of localization.
	 */
	title: string
	/**
	 * A human-readable explanation specific to this occurrence of the problem.
	 * Unlike the title, this field's content can vary by occurrence.
	 */
	detail: string
	/**
	 * A URI reference that identifies the specific occurrence of the problem.
	 * It may or may not yield further information if dereferenced.
	 */
	instance: string
}

/**
 * RFC 9457 Problem Details object.
 *
 * The generic parameter `TExtensions` allows you to type additional RFC "extension members"
 * alongside the standard fields:
 *
 * @example
 * ```ts
 * type ValidationProblem = ProblemDetails<{ errors: { field: string; message: string }[] }>
 * ```
 */
export type ProblemDetails<TExtensions extends Record<string, unknown> = Record<string, unknown>> =
	ProblemDetailsBase & TExtensions

/**
 * Used by named exception constructors. `type` and `instance` are required because they are
 * intended to be unique per problem occurrence; all other fields have sensible defaults.
 */
export type ProblemDetailsWithSomeDefaults<
	TExtensions extends Record<string, unknown> = Record<string, unknown>,
> = Partial<ProblemDetails<TExtensions>> & {
	type: string
	instance: string
}
